#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/atlauncher.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/atlauncher-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/atlauncher-pa.desktop
